apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: web
        image: mirrorgooglecontainers/pause:3.2 # 本地测试先用一个极轻量的pause镜像模拟，也可以换成你自己的API镜像
        resources:
          requests:
            cpu: "100m"     # 0.1核。这个是HPA计算比例的基准！
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend
