apiVersion: v1
kind: Service
metadata:
  name: postgres-service      # ⚡️还记得吗？Python 代码里配的 DB_HOST 就是这个名字
  namespace: default
  labels:
    app: postgres
spec:
  clusterIP: None             # ⚡️核心：None 代表这是 Headless Service，不分配统一的 VIP
  selector:
    app: postgres             # 绑定后面 StatefulSet 的 Pod
  ports:
  - port: 5432                # Postgres 默认端口
    name: postgres
