apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  labels:
    app: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: go-app:optimized
        imagePullPolicy: Never # force using local docker image
        ports:
        - containerPort: 8081
        env:
        - name: OTEL_TRACES_EXPORTER
          value: "none"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80       # Service port
      targetPort: 8081 # container internal port
      nodePort: 31080  # expose NodePort 31080